version: '3.1'

services:
  omdao:
    depends_on:
      - db
    build: .
    restart: always
    env_file:
      - ./.env
      - ./.env_web

  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdb_data:/var/lib/postgresql/data

  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    tty: true
    ports:
      - 443:443
      - 80:80
    logging:
      options:
        max-size: "100m"
        max-file: "100"
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - omdao

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./.env_letsencrypt
    logging:
      options:
        max-size: "100m"
        max-file: "100"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  pgdb_data:
  certs:
  html:
  vhost:
  acme: