version: '3.1'

services:
  omdao:
    depends_on:
      - db
    build: .
    restart: always
    ports:
      - 8000:8000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: omdao
      POSTGRES_USER: omdao
      POSTGRES_PASSWORD: omdao
    volumes:
      - pgdb_data:/var/lib/postgresql/data

volumes:
  pgdb_data: